name: Fcstatistics

on:
  workflow_dispatch:

jobs:
  build_and_publish_python:
    runs-on: ubuntu-latest
    env:
      PYPI_API_TOKEN: ${{ secrets.pypi-AgEIcHlwaS5vcmcCJDQyZjJjMzdlLWQxN2MtNDhkYS1hMWI1LTlhZjMyZDRmZTM1YwACFFsxLFsiZmNzdGF0aXN0aWNzIl1dAAIsWzIsWyI0YWZmYjViNy1iMzRhLTQ4MGItOTg3Mi03ZTQ3ZmYyZjNiNmUiXV0AAAYgYfL25EMGXOLyGZOjU9vw9shD-DuNb0qoVg1bdok_Zl8}}

    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6

      - name: Install dependencies
        run: pip3 install wheel twine

      - name: Build
        run: python3 setup.py sdist bdist_wheel

      - name: Publish to PyPI
        run: twine upload --repository-url https://upload.pypi.org/legacy/ -u __token__ -p ${pypi-AgEIcHlwaS5vcmcCJDQyZjJjMzdlLWQxN2MtNDhkYS1hMWI1LTlhZjMyZDRmZTM1YwACFFsxLFsiZmNzdGF0aXN0aWNzIl1dAAIsWzIsWyI0YWZmYjViNy1iMzRhLTQ4MGItOTg3Mi03ZTQ3ZmYyZjNiNmUiXV0AAAYgYfL25EMGXOLyGZOjU9vw9shD-DuNb0qoVg1bdok_Zl8} dist/*
